export default [
  {
    size: "32px",
    title: "H1 (Page header)",
    weight: "300",
    spacing: "",
    lineHeight: "40px",
  },
  {
    size: "28px",
    title: "H2 (Modal, Drawer Header)",
    weight: "300",
    spacing: "0.25px",
    lineHeight: "40px",
  },
  {
    size: "20px",
    title: "H3 (Small card title)",
    weight: "700",
    spacing: "0.15px",
    lineHeight: "24px",
  },
  {
    size: "20px",
    title: "H4 (Large card title)",
    weight: "400",
    spacing: "",
    lineHeight: "24px",
  },
  {
    size: "16px",
    title: "B1 (Primary body text)",
    weight: "400",
    spacing: "",
    lineHeight: "24px",
  },
  {
    size: "14px",
    title: "B2 (Clickable text)",
    weight: "600",
    spacing: "",
    lineHeight: "24px",
  },
  {
    size: "14px",
    title: "B3 (Button text)",
    weight: "700",
    spacing: "0.2px",
    lineHeight: "20px",
  },
  {
    size: "14px",
    title: "B4 (Hovers)",
    weight: "400",
    spacing: "",
    lineHeight: "20px",
  },
  {
    size: "12px",
    title: "Pills & Chips",
    weight: "700",
    spacing: "",
    lineHeight: "20px",
  },
  {
    size: "12px",
    title: "Forms",
    weight: "400",
    spacing: "",
    lineHeight: "16px",
  },
]
