swagger: "2.0"

# API information
info:
  title: Hux Customer Data Management (CDM)
  description:
    A REST API for Customer Data Management (CDM) platform.
  version: 1.0.0

# API paths
paths:
  /datafeeds:
    get:
      summary:
        Retrieves the datafeed catalog
      tags:
      - datafeeds
      produces:
      - application/json
      responses:
        200:
          description:
            OK
          schema:
            type: array
            items:
              $ref: "#/definitions/Datafeed"

  /datafeeds/{feed_id}:
    parameters:
    - name: feed_id
      in: path
      description: ID of datafeed catalog
      required: true
      type: integer
    get:
      summary:
        Retrieves the datafeed from the datafeed catalog by ID
      tags:
      - datafeeds
      produces:
      - application/json
      responses:
        200:
          description:
            OK
          schema:
            $ref: "#/definitions/Datafeed"
        404:
          description:
            Datafeed not found

  /fieldmappings:
    get:
      summary:
        Retrieves the fieldmappings for the datafeed catalog
      tags:
      - fieldmappings
      produces:
      - application/json
      responses:
        200:
          description:
            OK
          schema:
            type: array
            items:
              $ref: "#/definitions/Fieldmapping"
    post:
      summary:
        Creates and adds a new fieldmapping for the datafeed catalog
      tags:
      - fieldmappings
      produces:
      - application/json
      parameters:
      - name: body
        in: body
        description:
          Fieldmappings object that needs to be added for the datafeed catalog
        schema:
          $ref: "#/definitions/Fieldmapping"
        required: true
      responses:
        201:
          description:
            Created
          schema:
            $ref: "#/definitions/Fieldmapping"
        405:
          description:
            Validation exception
  /fieldmappings/{fieldmapping_id}:
    parameters:
      - name: fieldmapping_id
        in: path
        description: ID of fieldmapping
        required: true
        type: integer
    get:
      summary:
        Retrieves the fieldmapping for the datafeed catalog by ID
      tags:
      - fieldmappings
      responses:
        200:
          description:
            OK
          schema:
            $ref: "#/definitions/Fieldmapping"
        404:
          description:
            Fieldmapping not found
    put:
      summary:
        Updates an existing fieldmapping object for the datafeed catalog
      tags:
      - fieldmappings
      parameters:
      - name: body
        in: body
        description:
          Fieldmapping object that needs to be updated for the datafeed catalog
        schema:
          $ref: "#/definitions/Fieldmapping"
        required: true
      responses:
        200:
          description:
            Updated
          schema:
            $ref: "#/definitions/Fieldmapping"
        404:
          description:
            Fieldmapping not found
        405:
          description:
            Validation exception

# API components
definitions:
  Datafeed:
    type: object
    properties:
      feed_id:
        description:
          ID of the datafeed
        type: integer
        example: 7
      modified:
        description:
          Last modified date of the datafeed
        type: string
        format: date-time
        example: 2021-02-20T12:23:45.678+00:00
      data_source:
        description:
          Source of the data for the datafeed
        type: string
        example: "Salesforce"
      data_type:
        description:
          Type of data for the datafeed
        type: string
        example: "Customers"
        enum:
          - "Customers"
          - "Orders"
          - "Items"
      feed_type:
        description:
          Type of datafeed
        type: string
        example: "API"
        enum:
          - "Batch"
          - "API"
      file_extension:
        description:
          File extension of the datafeed
        type: string
        example: "json"
        enum:
          - "csv"
          - "json"
      is_pii:
        description:
          Indicate whether the type of data contains personally identifiable
          information (PII)
        type: boolean
        example: True

  Fieldmapping:
    type: object
    properties:
      id:
        description:
          ID of the fieldmapping
        type: integer
        example: 12
      modified:
        description:
          Last modified date of the field mapping
        type: string
        format: date-time
        example: 2021-02-20T12:23:45.678+00:00
      field_name:
        description:
          Name of the field to map to (ie. standardized field name)
        type: string
        enum:
        - "FNAME"
        - "LNAME"
        - "ADD1"
        - "ADD2"
        - "ADD3"
        - "CITY"
        - "STATE"
        - "ZIP"
        - "COMPANY"
        - "TITLE"
        - "EMAIL"
        example: "FNAME"
      field_variation:
        description:
          Name of the field in the originating data feed (ie. source field name)
        type: string
        example: "First Name"
