export default [
  {
    size: "28px",
    title: "H1 (Large) (Main Pages)",
    weight: "300",
    spacing: "",
    lineHeight: "40px",
  },
  {
    size: "24px",
    title: "H2 (Models & Drawers)",
    weight: "300",
    spacing: "",
    lineHeight: "40px",
  },
  {
    size: "18px",
    title: "H3 (Sm) (Sectionals)",
    weight: "400",
    spacing: "",
    lineHeight: "25px",
  },
  {
    size: "18px",
    title: "H4 (Card Headers)",
    weight: "300",
    spacing: "",
    lineHeight: "24px",
  },
  {
    size: "16px",
    title: "B1 (Reg)",
    weight: "400",
    spacing: "",
    lineHeight: "22px",
  },
  {
    size: "14px",
    title: "B2 (Sm) - Hovers & Labels",
    weight: "400",
    spacing: "",
    lineHeight: "16px",
  },
  {
    size: "16px",
    title: "Button Text",
    weight: "400",
    spacing: "",
    lineHeight: "20px",
  },
  {
    size: "16px",
    title: "Metric #s",
    weight: "600",
    spacing: "",
    lineHeight: "22px",
  },
  {
    size: "12px",
    title: "Pill Text",
    weight: "600",
    spacing: "",
    lineHeight: "16px",
  },
  {
    size: "16px",
    title: "'optional'",
    weight: "600",
    spacing: "",
    lineHeight: "22px",
  },
  {
    size: "14px",
    title: "Nav > Headers",
    weight: "400",
    spacing: "",
    lineHeight: "16px",
  },
  {
    size: "14px",
    title: "Nav > Menu item 1",
    weight: "400",
    spacing: "",
    lineHeight: "22px",
  },
]
