# .github/release.yml

changelog:
  categories:
    - title: App Release
      labels:
        - Branch naming convention- release-x.x.x, example-"release-6.0.1"
        - Tag convention- app-vX.X.X, example-"app-v6.0.0"
    - title: DB Release
      labels:
        - Tag convention- lib-vX.X.X, example-"lib-v6.0.0"
