export default [
  "Add",
  "Address",
  "Age",
  "Alerts - New",
  "Alerts",
  "Application",
  "Audiences",
  "Calendar",
  "Checkmark",
  "Cities",
  "Client dashboard",
  "Close & Remove",
  "CommercePersonalization",
  "Configuration",
  "Contact us",
  "Cookie",
  "Countries",
  "Customers",
  "Data sources",
  "Delete",
  "Deliver",
  "Destinations",
  "Drag & drop - vertical",
  "Drag & drop horizontal",
  "Dropdown - down",
  "Dropdown - left",
  "Dropdown - right",
  "Dropdown - up",
  "Edit",
  "Email Deliverability",
  "Email",
  "Engagements",
  "Error & Warning",
  "Error",
  "Existing data extension",
  "Exit",
  "Experience data platform",
  "Favorite - Selected",
  "Favorite",
  "Feedback",
  "Filter",
  "Financial",
  "Guide",
  "HX TrustID score",
  "Help",
  "Hide",
  "History",
  "Home",
  "IDR",
  "Icon Placeholder",
  "Informative",
  "Intelligentmarketing",
  "Issue",
  "List",
  "Locked",
  "Lookalike",
  "Manual",
  "Many people",
  "Map",
  "Menu",
  "Model - Email",
  "Model - Other",
  "Model - Retention",
  "Model - Sales forecasting",
  "Model - Segmentation",
  "Model - Web",
  "Models",
  "New data extension",
  "Null & Empty",
  "Offline",
  "Open in new",
  "Person",
  "Phone",
  "Recurring & repeating",
  "Refresh",
  "Search.AI",
  "Search",
  "Segment Playground",
  "Sort - backwards",
  "Sort",
  "Spaceship (Lost)",
  "States",
  "Team member",
  "Time",
  "View",
  "Web traffic",
  "World &Geographic",
  "automotive",
  "healthcare",
  "hospitality",
  "retail",
]