# This is the CI pipeline for Unified Solution UI Integration tests

version: "1.0"

stages:
  - prepare
  - git
  - set_env
  - docker
  - checks
  - artifactory

steps:
  PrepareBuildDetails:
    stage: prepare
    title: Prepare Build Details
    type: parallel
    steps:
      GetTriggerName:
        stage: prepare
        title: get trigger name using id from spec yaml
        type: deloittehux/get-trigger-name

  CloneRepository:
    stage: git
    title: Cloning ${{CF_REPO_NAME}} repository...
    type: git-clone
    repo: "${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}"
    revision: "${{CF_BRANCH}}" # Git branch triggering the pipeline

  SetEnvironment:
    stage: set_env
    title: Set environment variables
    type: freestyle
    image: huxhub.repo.mgnt.in/alpine
    working_directory: "${{CF_REPO_NAME}}"
    commands:
      - cat ./hux/integration_tests/frontend/ci/$TRIGGER_NAME/config.env >> ${{CF_VOLUME_PATH}}/env_vars_to_export

  BuildImage:
    stage: docker
    title: Building image for UI integration tests.
    type: "build"
    image_name: "${{BUILD_NAME}}"
    working_directory: "${{CF_REPO_NAME}}/${{UI_INTEGRATION_TEST_PATH}}"
    dockerfile: "Dockerfile"
    tag: "${{DOCKER_TAG}}"

  Checks:
    stage: checks
    title: Running checks for lint and style.
    type: parallel
    steps:
      lint:
        title: "Running lint."
        image: ${{BuildImage}}
        working_directory: /app
        commands:
          - npm run lint
      style:
        title: "Running style."
        image: ${{BuildImage}}
        working_directory: /app
        commands:
          - npm run style

  PublishToArtifactory:
    stage: artifactory
    title: Publish Unified UI Image to JFrog Artifactory
    type: deloittehux/jfrog-docker-publish
    arguments:
      BUILD_NAME: "${{BUILD_NAME}}"
      BUILD_NUMBER: "${{DOCKER_TAG}}"
      JFROG_REGISTRY: "${{JFROG_REGISTRY}}"
      BUILD_TAG: "${{DOCKER_TAG}}"
    when:
      branch:
        only:
          - main
          - /^app.*/i
