import colors from "./colors"

export default {
  primary: colors.darkBlue,
  secondary: colors.blue,
  tertiary: colors.white,
  error: colors.red,
  info: colors.blue,
  success: colors.green,
  warning: colors.yellow,
  black: colors.black,
  white: colors.white,
  aliceBlue: colors.aliceBlue,
  anchor: colors.lightBlue,
  background: colors.backgroundBlue,
  pantoneBlue: colors.pantoneBlue,
  zircon: colors.zircon,
  neroBlack: colors.neroBlack,
  gray: colors.gray,
  darkGrey: colors.darkGrey,
  lightGrey: colors.lightGrey,
  columbiaBlue: colors.columbiaBlue,
  skyBlue: colors.skyBlue,
  greyBlue: colors.greyBlue,
  pinkLittleDark: colors.pinkLittleDark,
  darkGreyHeading: colors.darkGreyHeading,
  lightGreyAnotherVariant: colors.lightGreyAnotherVariant,
  offWhite: colors.offWhite,
  pillBlue: colors.dullBlue,
  persianGreen: colors.persianGreen,
  appBodyGrey: colors.appBodyGrey,
  smoke: colors.smoke,
  cerulean: colors.cerulean,
  tealBlue: colors.tealBlue,
}
