---
test_name: Test notifications API default success

strict:
  - json:list_any_order

includes:
  - !include common.yaml

stages:
  - name: test notifications api default success

    # Define the request to be made...
    request:
      url: "{host}/{version}/notifications"
      method: GET
      headers:
        content-type: application/json
        Authorization: "Bearer {token}"

    # ...and the expected response code and body
    response:
      strict: false
      status_code: 200
      headers:
        content-type: application/json
      json:
        notifications: !anylist
          - id: !anystr
            notification_type: !re_fullmatch "(Success|Critical|Informational)"
            description: !anystr
            category: !anystr
            created: !re_fullmatch "(\\d{4})-(\\d{2})-(\\d{2})T(\\d{2})\\:(\\d{2})\\:(\\d{2})\\.(\\d{3})Z"

---
test_name: Test notifications API custom query params success

strict:
  - json:list_any_order

includes:
  - !include common.yaml

stages:
  - name: test notifications api custom query params success

    # Define the request to be made...
    request:
      url: "{host}/{version}/notifications?batch_size=4&sort_order=ascending&batch_number=2"
      method: GET
      headers:
        content-type: application/json
        Authorization: "Bearer {token}"

    # ...and the expected response code and body
    response:
      strict: false
      status_code: 200
      headers:
        content-type: application/json
      json:
        notifications: !anylist
          - id: !anystr
            notification_type: !re_fullmatch "(Success|Critical|Informational)"
            description: !anystr
            category: !anystr
            created: !re_fullmatch "(\\d{4})-(\\d{2})-(\\d{2})T(\\d{2})\\:(\\d{2})\\:(\\d{2})\\.(\\d{3})Z"

---
test_name: Test notifications API failure

strict:
  - json:list_any_order

includes:
  - !include common.yaml

stages:
  - name: test notifications api failure

    # Define the request to be made...
    request:
      url: "{host}/{version}/notifications?sort_order=desc"
      method: GET
      headers:
        content-type: application/json
        Authorization: "Bearer {token}"

    # ...and the expected response code and body
    response:
      strict: false
      status_code: 400
      headers:
        content-type: application/json
      json:
        message: "Invalid or incomplete arguments received"
