---
test_name: Test API Spec

strict:
  - json:list_any_order

includes:
  - !include common.yaml

stages:
  - name: Open API Spec Check

    # Define the request to be made...
    request:
      url: "{host}/{openapi}.json"
      method: GET

    # ...and the expected response code and body
    response:
      strict: False
      status_code: 200
      headers:
        content-type: application/json
      json:
        info:
          version: !anystr
          title: "Hux API"
        paths: !anydict
        definitions: !anydict
        schemes:
          - "https"
        securityDefinitions:
          Bearer:
            type: "apiKey"
            name: "Authorization"
            in: "header"
