---
test_name: Test API Spec

strict:
  - json:list_any_order

includes:
  - !include common.yaml

stages:
  - name: Open API Spec Check

    # Define the request to be made...
    request:
      url: "{host}/{openapi}.json"
      method: GET

    # ...and the expected response code and body
    response:
      strict: False
      status_code: 200
      headers:
        content-type: application/json
      json:
        info:
          version: !anystr
          title: "Hux API"
        paths:
          /api/v1/audiences: !anydict
          /api/v1/audiences/rules: !anydict
          /api/v1/audiences/{audience_id}: !anydict
          /api/v1/audiences/{audience_id}/deliver: !anydict
          /api/v1/audiences/{audience_id}/delivery-history: !anydict
          /api/v1/audiences/{audience_id}/{download_type}: !anydict
          /api/v1/customers: !anydict
          /api/v1/customers-insights/cities: !anydict
          /api/v1/customers-insights/demo: !anydict
          /api/v1/customers-insights/geo: !anydict
          /api/v1/customers-insights/states: !anydict
          /api/v1/customers-insights/total: !anydict
          /api/v1/customers/overview: !anydict
          /api/v1/customers/{hux_id}: !anydict
          /api/v1/customers/{hux_id}/events: !anydict
          /api/v1/data-sources: !anydict
          /api/v1/data-sources/{data_source_id}: !anydict
          /api/v1/destinations: !anydict
          /api/v1/destinations/constants: !anydict
          /api/v1/destinations/validate: !anydict
          /api/v1/destinations/{destination_id}: !anydict
          /api/v1/destinations/{destination_id}/data-extensions: !anydict
          /api/v1/engagements: !anydict
          /api/v1/engagements/{engagement_id}: !anydict
          /api/v1/engagements/{engagement_id}/audience-performance/display-ads: !anydict
          /api/v1/engagements/{engagement_id}/audience-performance/download: !anydict
          /api/v1/engagements/{engagement_id}/audience-performance/email: !anydict
          /api/v1/engagements/{engagement_id}/audience/{audience_id}/deliver: !anydict
          /api/v1/engagements/{engagement_id}/audience/{audience_id}/destination/{destination_id}/campaign-mappings: !anydict
          /api/v1/engagements/{engagement_id}/audience/{audience_id}/destination/{destination_id}/campaigns: !anydict
          /api/v1/engagements/{engagement_id}/audience/{audience_id}/destination/{destination_id}/deliver: !anydict
          /api/v1/engagements/{engagement_id}/audience/{audience_id}/destinations: !anydict
          /api/v1/engagements/{engagement_id}/audiences: !anydict
          /api/v1/engagements/{engagement_id}/deliver: !anydict
          /api/v1/engagements/{engagement_id}/delivery-history: !anydict
          /api/v1/idr/datafeeds: !anydict
          /api/v1/idr/datafeeds/{datafeed_id}: !anydict
          /api/v1/idr/matching-trends: !anydict
          /api/v1/idr/overview: !anydict
          /api/v1/lookalike-audiences: !anydict
          /api/v1/metrics: !anydict
          /api/v1/models: !anydict
          /api/v1/models/{model_id}/drift: !anydict
          /api/v1/models/{model_id}/feature-importance: !anydict
          /api/v1/models/{model_id}/features: !anydict
          /api/v1/models/{model_id}/lift: !anydict
          /api/v1/models/{model_id}/overview: !anydict
          /api/v1/models/{model_id}/version-history: !anydict
          /api/v1/notifications: !anydict
          /api/v1/users/profile: !anydict
          /api/v1/{component_name}/{component_id}/favorite: !anydict
        definitions:
          AudienceDeliveryHistorySchema: !anydict
          AudienceGetSchema: !anydict
          CampaignMappingSchema: !anydict
          CampaignSchema: !anydict
          CdpDataSourceSchema: !anydict
          CustomerDemographicInsightsSchema: !anydict
          CustomerEventsSchema: !anydict
          CustomerGeoVisualSchema: !anydict
          CustomerOverviewSchema: !anydict
          CustomerProfileSchema: !anydict
          CustomersInsightsCitiesSchema: !anydict
          CustomersInsightsStatesSchema: !anydict
          CustomersSchema: !anydict
          DataFeedDetailsSchema: !anydict
          DataFeedSchema: !anydict
          DestinationConstantsSchema: !anydict
          DestinationDataExtGetSchema: !anydict
          DestinationGetSchema: !anydict
          EngagementDeliveryHistorySchema: !anydict
          EngagementGetSchema: !anydict
          IDROverviewWithDateRangeSchema: !anydict
          LookalikeAudienceGetSchema: !anydict
          MatchingTrendsSchema: !anydict
          ModelDashboardSchema: !anydict
          ModelDriftSchema: !anydict
          ModelLiftSchema: !anydict
          ModelSchema: !anydict
          ModelVersionSchema: !anydict
          NotFoundError: !anydict
          NotificationsSchema: !anydict
          TotalCustomersInsightsSchema: !anydict
          UnAuth401Schema: !anydict
          UserSchema: !anydict
        schemes:
          - "https"
        securityDefinitions:
          Bearer:
            type: "apiKey"
            name: "Authorization"
            in: "header"
