---
test_name: Test Audience Rules API

strict:
  - json:list_any_order

includes:
  - !include common.yaml

stages:
  - name: Test Retrieving Audience Rules

    # Define the request to be made...
    request:
      url: "{host}/{version}/audiences/rules"
      method: GET
      headers:
        content-type: application/json
        Authorization: "Bearer {token}"

    response:
      strict: false
      status_code: 200
      headers:
        content-type: application/json
      json:
        text_operators:
          contains: "Contains"
          does_not_contain: "Does not contain"
          equals: "Equals"
          does_not_equal: "Does not equal"
        rule_attributes:
          model_scores:
            propensity_to_unsubscribe:
              name: !anystr
              type: !anystr
              min: !anyfloat
              max: !anyfloat
              steps: !anyfloat
            ltv_predicted:
              name: !anystr
              type: !anystr
              min: !anyint
              max: !anyint
              steps: !anyint
            propensity_to_purchase:
              name: !anystr
              type: !anystr
              min: !anyfloat
              max: !anyfloat
              steps: !anyfloat
          general:
            age:
              name: !anystr
              type: !anystr
              min: !anyint
              max: !anyint
            email:
              name: !anystr
              type: !anystr
            gender:
              name: !anystr
              type: !anystr
              options: !anylist
            location:
              name: !anystr
              country:
                name: !anystr
                type: !anystr
                options: !anylist
              state:
                name: !anystr
                type: !anystr
                options: !anylist
              city:
                name: !anystr
                type: !anystr
                options: !anylist
              zip_code:
                name: !anystr
                type: !anystr



---
test_name: Test Retrieve all audiences API

strict:
  - json:list_any_order

includes:
  - !include common.yaml

stages:
  - name: Test Retrieving all audiences

    # Define the request to be made...
    request:
      url: "{host}/{version}/audiences"
      method: GET
      headers:
        content-type: application/json
        Authorization: "Bearer {token}"
      json:
        lookalikeable: "false"
        deliveries: "2"

    response:
      status_code: 200
      headers:
        content-type: application/json


---
test_name: Test retrieve non existant audience

strict:
  - json:list_any_order

includes:
  - !include common.yaml

stages:
  - name: Test Retrieving an audience that does not exist

    # Define the request to be made...
    request:
      url: "{host}/{version}/audiences/61135de24af31a0f33029092"
      method: GET
      headers:
        content-type: application/json
        Authorization: "Bearer {token}"

    response:
      status_code: 404
      headers:
        content-type: application/json

---
test_name: Test create - update - delete an audience

strict:
  - json:list_any_order

includes:
  - !include common.yaml

stages:
  - name: Retrieve data sources for and get an id

    request:
      url: "{host}/{version}/data-sources"
      method: GET
      headers:
        content-type: application/json
        Authorization: "Bearer {token}"

    response:
      strict: false
      status_code: 200
      headers:
        content-type: application/json
      json:
        !anylist
        - id: !anystr
          name: !anystr
          type: !anystr
          status: !anystr
          category: !anystr
          feed_count: !anyint
          is_enabled: !anybool
          is_added: !anybool
      save:
        $ext:
          function: tavern_test_utils:get_destination_by_name


  - name: Create the new audience

    # Define the request to be made...
    request:
      url: "{host}/{version}/audiences"
      method: POST
      headers:
        content-type: application/json
        Authorization: "Bearer {token}"
      json:
        name: "TAVERN_TEST_AUDIENCE"
        destinations:
          - id: "{destination.id}"
            delivery_platform_config:
              data_extension_name: "txt"
        engagements: []
        filters:
          - section_aggregator: "ALL"
            section_filters:
              - field: "filter_field"
                type: "value"
                value: "value"

    response:
      status_code: 201
      headers:
        content-type: application/json
      save:
        json:
          audience_id: "id"

  - name: Update the new audience
      # Define the request to be made...
      request:
        url: "{host}/{version}/audiences/{audience_id}"
        method: PUT
        headers:
          content-type: application/json
          Authorization: "Bearer {token}"
        json:
          name: "TAVERN_TEST_AUDIENCE_UPDATED"
          destinations:
            - id: "{destination.id}"
              delivery_platform_config:
                data_extension_name: "txt"
          engagements: [ ]
          filters:
            - section_aggregator: "ALL"
              section_filters:
                - field: "filter_field"
                  type: "value"
                  value: "value"

      response:
        strict: false
        status_code: 200
        headers:
          content-type: application/json
        json:
          name: "TAVERN_TEST_AUDIENCE_UPDATED"

  - name: Delete the new audience
      # Define the request to be made...
      request:
        url: "{host}/{version}/audiences/{audience_id}"
        method: DELETE
        headers:
          content-type: application/json
          Authorization: "Bearer {token}"

      response:
        strict: false
        status_code: 204
        headers:
          content-type: application/json
