---
test_name: Test user get success

strict:
  - json:list_any_order

includes:
  - !include common.yaml

stages:
  - name: test user get success

    # Define the request to be made...
    request:
      url: "{host}/{version}/users/profile"
      method: GET
      headers:
        content-type: application/json
        Authorization: "Bearer {token}"

    # ...and the expected response code and body
    response:
      strict: false
      status_code: 200
      headers:
        content-type: application/json
      json: {}
