---
test_name: Test notifications default success

strict:
  - json:list_any_order

includes:
  - !include common.yaml

stages:
  - name: test notifications default success

    # Define the request to be made...
    request:
      url: "{host}/{version}/notifications"
      method: GET
      headers:
        content-type: application/json
        Authorization: "Bearer {token}"

    # ...and the expected response code and body
    response:
      strict: false
      status_code: 200
      headers:
        content-type: application/json
      json:
        - id: !anystr
        - notification_type: !anystr
        - description: !anystr
        - created: !re_fullmatch "(\\d{4})-(\\d{2})-(\\d{2})T(\\d{2})\\:(\\d{2})\\:(\\d{2})\\.(\\d{3})Z"

---
test_name: Test notifications custom success

strict:
  - json:list_any_order

includes:
  - !include common.yaml

stages:
  - name: test notifications custom success

    # Define the request to be made...
    request:
      url: "{host}/{version}/notifications?batch_size=4&sort_order=ascending&batch_number=1"
      method: GET
      headers:
        content-type: application/json
        Authorization: "Bearer {token}"

    # ...and the expected response code and body
    response:
      strict: false
      status_code: 200
      headers:
        content-type: application/json
      json:
        - id: !anystr
        - notification_type: !re_fullmatch "(Success|Critical|Informational)"
        - description: !anystr
        - created: !re_fullmatch "(\\d{4})-(\\d{2})-(\\d{2})T(\\d{2})\\:(\\d{2})\\:(\\d{2})\\.(\\d{3})Z"

---
test_name: Test notifications failure

strict:
  - json:list_any_order

includes:
  - !include common.yaml

stages:
  - name: test notifications failure

    # Define the request to be made...
    request:
      url: "{host}/{version}/notifications?sort_order=desc"
      method: GET
      headers:
        content-type: application/json
        Authorization: "Bearer {token}"

    # ...and the expected response code and body
    response:
      strict: false
      status_code: 400
      headers:
        content-type: application/json
      json:
        message: "Invalid or incomplete arguments received"
