openapi: 3.0.2

# API information
info:
  title: Hux Customer Data Management (CDM)
  description:
    A REST API for Customer Data Management (CDM) platform.
  version: 1.0.0

# API servers
servers:
  - url: /api/v1/cdm

# API tags
tags:
  - name: datafeeds
    description:
      Operations related to managing the datafeed catalog
  - name: fieldmappings
    description:
      Operations related to managing a datafeed's PII fieldmappings

# API paths
paths:
  /datafeeds:
    get:
      summary:
        Retrieves the datafeed catalog
      tags:
      - datafeeds
      responses:
        200:
          description:
            OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Datafeed"

  /datafeeds/{feed_id}:
    parameters:
      - name: feed_id
        in: path
        description: ID of datafeed catalog
        required: true
        style: simple
        explode: false
        schema:
          type: integer
    get:
      summary:
        Retrieves the datafeed from the datafeed catalog by ID
      tags:
      - datafeeds
      responses:
        200:
          description:
            OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Datafeed"
        404:
          description:
            Datafeed not found

  /fieldmappings:
    get:
      summary:
        Retrieves the fieldmappings for the data feed catalog
      tags:
      - fieldmappings
      responses:
        200:
          description:
            OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Fieldmappings"
        404:
          description:
            Fieldmappings not found
    post:
      summary:
        Creates and adds fieldmappings for the data feed catalog
      tags:
      - fieldmappings
      requestBody:
        description:
          Fieldmappings object that needs to be added for the data feed catalog
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Fieldmappings"
        required: true
      responses:
        201:
          description:
            Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Fieldmappings"
    put:
      summary:
        Update an existing fieldmapping object for the data feed catalog
      tags:
      - fieldmappings
      requestBody:
        description:
          Fieldmappings object that needs to be updated for the data feed catalog
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Fieldmappings"
        required: true
      responses:
        200:
          description:
            Updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Fieldmappings"
        404:
          description:
            fieldmapping not found
        405:
          description:
            Validation exception

# API components
components:
  schemas:
    Datafeed:
      allOf:
        - $ref: '#/components/schemas/DatafeedBody'
        - type: object
          properties:
            feed_id:
              description:
                ID of the datafeed
              type: integer
              example: 7
            modified:
              description:
                Last modified date of the datafeed
              type: string
              format: date-time
              example: 2021-02-20T12:23:45.678+00:00

    DatafeedBody:
      type: object
      properties:
        data_source:
          description:
            Source of the data for the datafeed
          type: string
          example: "Salesforce"
        data_type:
          description:
            Type of data for the datafeed
          type: string
          example: "Customers"
          enum:
            - "Customers"
            - "Orders"
            - "Items"
        feed_type:
          description:
            Type of datafeed
          type: string
          example: "API"
          enum:
            - "Batch"
            - "API"
        file_extension:
          description:
            File extension of the datafeed
          type: string
          example: "json"
          enum:
            - "csv"
            - "json"
        is_pii:
          description:
            Indicate whether the type of data contains personally identifiable
            information (PII)
          type: boolean
          example: True

    Fieldmappings:
      type: object
      properties:
        feed_id:
          description:
            ID of the datafeed these fieldmappings are associated with
          type: integer
          example: 7
        fields:
          description:
            List of fields for the data feed catalog that contains PII
          type: array
          items:
            $ref: "#/components/schemas/Fields"

    Fields:
      type: object
      properties:
        id:
          description:
            ID of the fieldmapping
          type: integer
          example: 12
        field_name:
          description:
            Name of the field to map to (ie. standardized field name)
          type: string
          enum:
          - "FNAME"
          - "LNAME"
          - "ADD1"
          - "ADD2"
          - "CITY"
          - "STATE"
          - "ZIP"
          example: "FNAME"
        field_variation:
          description:
            Name of the field in the originating data feed (ie. source field name)
          type: string
          example: "First Name"
        modified:
          description:
            Last modified date of the field mapping
          type: string
          format: date-time
          example: 2021-02-20T12:23:45.678+00:00
