{
 "title": "Unified Backend API",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Endpoint Response Times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "POST Endpoints",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hux_unified_requests_by_status_and_path_sum{status=~\"200|201|202|204\", method=\"POST\"} /hux_unified_requests_by_status_and_path_count{status=~\"200|201|202|204\", method=\"POST\"}",
     "legendFormat": "{{status}} - {{path}}"
    }
   ]
  },
  {
   "title": "GET Endpoints",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hux_unified_requests_by_status_and_path_sum{status=~\"200|201|202|204\", method=\"GET\"} /hux_unified_requests_by_status_and_path_count{status=~\"200|201|202|204\", method=\"GET\"}",
     "legendFormat": "{{status}} - {{path}}"
    }
   ]
  },
  {
   "title": "PATCH/PUT Endpoints",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hux_unified_requests_by_status_and_path_sum{status=~\"200|201|202|204\", method=~\"PATCH|PUT\"} /hux_unified_requests_by_status_and_path_count{status=~\"200|201|202|204\", method=~\"PATCH|PUT\"}",
     "legendFormat": "{{status}} - {{method}} - {{path}}"
    }
   ]
  },
  {
   "title": "DELETE Endpoints",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hux_unified_requests_by_status_and_path_sum{status=~\"200|201|202|204\", method=\"DELETE\"} /hux_unified_requests_by_status_and_path_count{status=~\"200|201|202|204\", method=\"DELETE\"}",
     "legendFormat": "{{status}} - {{path}}"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Error Code Counts",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hux_unified_requests_by_status_and_path_count{status!~\"200|201|202|204\"}",
     "legendFormat": "{{status}} - {{method}} - {{path}}"
    }
   ]
  }
 ]
}