version: "1.0"
stages:
  - clone
  - checks

steps:

  clone:
    stage: "clone"
    title: "Cloning repository"
    type: "git-clone"
    repo: "DeloitteHux/hux-unified"
    revision: "${{CF_BRANCH}}"
    git: "DeloitteHux_github"

  checks:
    stage: "checks"
    image: 'huxhub.repo.mgnt.in/tox-ci'
    working_directory: '/codefresh/volume/${{CF_REPO_NAME}}/scripts'
    description: run tests using tox
    commands:
     - tox -e ${TOXENV} -- --skip-model-generate
    scale:
      py37:
        title: "py37 Unit tests"
        environment:
          - TOXENV=py37
      safety:
        title: "Safety Checks"
        environment:
          - TOXENV=safety
      style:
        title: "style Checks"
        environment:
          - TOXENV=style
      checkCoverage:
        title: "coverage check"
        environment:
          - TOXENV=checkCoverage
    fail_fast: false
