version: "1.0"
stages:
  - clone
  - checks

steps:

  clone:
    stage: "clone"
    title: "Cloning repository"
    type: "git-clone"
    repo: "DeloitteHux/hux-unified"
    revision: "${{CF_BRANCH}}"
    git: "DeloitteHux_github"

  checks:
    stage: "checks"
    image: 'huxhub.repo.mgnt.in/tox-ci'
    working_directory: '/codefresh/volume/${{CF_REPO_NAME}}/scripts'
    description: run tests using tox
    commands:
      - pip install tox
      - python -m tox -e ${TOXENV}
    scale:
      py37:
        environment:
          - TOXENV=py37
      safety:
        environment:
          - TOXENV=safety
      style:
        environment:
          - TOXENV=style
      checkCoverage:
        environment:
          - TOXENV=checkCoverage
    fail_fast: false
