export default [
  "AWS S3",
  "Adobe Campaign",
  "Adobe Experience Platform",
  "Algorthmia",
  "Amazon aurora",
  "Amazon",
  "Amplitude",
  "Aol",
  "Apache Airflow",
  "Apache Hive",
  "Apache Sparks",
  "Aqfer",
  "Azure SQL DB",
  "Azure",
  "Binderhub",
  "Bing",
  "Bluecore",
  "DEL_Favicons_Standard-black_circular",
  "DEL_Favicons_Standard-white_circular",
  "Disney",
  "Docker",
  "Dropbox",
  "Facebook",
  "Fullstory",
  "Gmail",
  "Google Ads",
  "Google Analytics",
  "Google BigQuery DB",
  "Google Cloud",
  "Google DV360",
  "Google Marketing Cloud",
  "Google Sheets",
  "Google",
  "Grafana",
  "HX TrustID-1",
  "HX TrustID-2",
  "HX TrustID-3",
  "HX TrustID-4",
  "HX TrustID",
  "Http",
  "Hubspot",
  "Hux",
  "IBM DB",
  "IBM",
  "Insight IQ",
  "Instagram",
  "Jira",
  "Juniper Labs",
  "Jupyterhub",
  "Kubeflow",
  "Kubernetes",
  "Linkedin",
  "Litmus",
  "LiveRamp",
  "MailChimp",
  "Mandrill",
  "Maria DB",
  "Marketo",
  "Matillion",
  "Medallia",
  "Microsoft Dynamics",
  "Microsoft Excel",
  "Microsoft Outlook",
  "Microsoft Power BI",
  "Microsoft Sharepoint",
  "Microsoft ads",
  "Mongo DB",
  "MySQL",
  "NetSuite",
  "OData",
  "Oracle DB",
  "Oracle",
  "Paypal",
  "Pendleton",
  "Pinterest",
  "Prometheus",
  "Qualtrics",
  "Quantum Metric",
  "Quickbooks",
  "REST API",
  "SAP HANA",
  "SAP",
  "SFTP",
  "Salesforce CDP",
  "Salesforce Commerce Cloud",
  "Salesforce Datorama",
  "Salesforce Marketing Cloud",
  "Salesforce",
  "SendGridbyTwilio",
  "ServiceNow",
  "Shopify",
  "Snapchat",
  "Snowflake",
  "Sparkpost",
  "Square",
  "Stripe",
  "Sugar CRM",
  "Surveymonkey",
  "Tableau",
  "Tecton",
  "TheTradeDesk",
  "Twilio",
  "Twitter",
  "Windows",
  "Yahoo",
  "Youtube",
  "Zendesk CRM",
  "Zoho CRM",
]
