export default [
  {
    icon: "home",
    enabled: true,
    label: "Home",
    name: "Home",
    link: { name: "Home" },
  },
  {
    icon: "configuration",
    enabled: true,
    label: "Configuration",
    name: "Configuration",
    defaultState: { configurationModels: [] },
    link: { name: "Configuration" },
  },
  {
    enabled: true,
    name: "Data Management",
    children: [
      {
        enabled: true,
        label: "Data Sources",
        icon: "datasource",
        name: "Data Sources",
        defaultState: { items: {}, dataFeedsDetails: [] },
        link: { name: "DataSources" },
      },
      {
        enabled: true,
        label: "Identity Resolution",
        icon: "identity-resolution",
        name: "Identity Resolution",
        defaultState: {
          overview: {},
          timeFrame: {},
          dataFeeds: {},
          dataFeedReports: {},
          matchingTrends: [],
        },
        link: { name: "Identity" },
      },
    ],
  },
  {
    enabled: true,
    name: "Decisioning",
    children: [
      {
        enabled: true,
        label: "Models",
        icon: "models",
        name: "Models",
        defaultState: {
          items: {},
          overview: {},
          history: {},
          lift: [],
          features: [],
          drift: [],
          modelFeatures: [],
          pipelinePreformance: {},
        },
        link: { name: "Models" },
      },
    ],
  },
  {
    enabled: true,
    name: "Orchestration",
    children: [
      {
        enabled: true,
        label: "Destinations",
        icon: "multiple_map_pins",
        name: "Destinations",
        defaultState: { items: {}, constants: {}, dataExtensions: [] },
        link: { name: "Destinations" },
      },
      {
        enabled: true,
        label: "Segment Playground",
        icon: "playground",
        name: "Segment Playground",
        link: { name: "SegmentPlayground" },
      },
      {
        enabled: true,
        label: "Audiences",
        icon: "audiences",
        name: "Audiences",
        defaultState: {
          audiences: [],
          newAudience: {
            name: "",
            engagements: [],
            attributeRules: [],
            destinations: [],
          },
          constants: {},
          deliveries: {},
          filteredDeliveries: [],
          demographics: {},
          geoCities: [],
          geoCountries: [],
          geoStates: [],
        },
        link: { name: "Audiences" },
      },
      {
        enabled: true,
        label: "Engagements",
        icon: "speaker_up",
        name: "Engagements",
        defaultState: {
          items: {},
          audiencePerformance: { ads: {}, email: {} },
          deliveries: {},
          filteredDeliveries: [],
          campaignMappingOptions: {},
          campaignMappings: [],
        },
        link: { name: "Engagements" },
      },
    ],
  },
  {
    enabled: true,
    name: "Insights",
    children: [
      {
        enabled: true,
        label: "Customers",
        icon: "customer-profiles",
        name: "Customers",
        defaultState: {
          items: {},
          overview: {},
          insights: null,
          totalCustomers: [],
          totalCustomerSpend: [],
          geoOverview: [],
          geoCities: [],
          geoCountries: [],
          geoStates: [],
          demographics: {},
          events: [],
        },
        link: { name: "Customers" },
      },
      {
        name: "HX TrustID",
        icon: "hx-trustid",
        superscript: "TM",
        label: "HX TrustID",
        enabled: true,
        defaultState: {
          trustIdOverview: null,
          segmentComparison: [],
          addSegment: [],
          trustIdAttributes: [],
        },
        link: { name: "HXTrustID" },
      },
      {
        enabled: true,
        label: "Email Deliverability",
        icon: "email_deliverability",
        name: "Email Deliverability",
        defaultState: {
          domain: {
            sent: [],
            open_Rate: [],
            delivered_rate: [],
            click_rate: [],
            unsubscribe_rate: [],
            complaints_rate: [],
          },
          overview: {},
        },
        link: { name: "EmailDeliverability" },
      },
    ],
  },
]
