name: Black Linting
on: [pull_request]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install Black
        run: pip install black
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            api:
              - 'hux/api/huxunify/**'
            docs:
              - 'docs/source/conf.py'
            dblib:
              - 'lib/huxunifylib-database/huxunifylib/**'
            scripts:
              - 'scripts/database/**'
            api_int_tests:
              - 'hux/integration_tests/api/**'

      - if: steps.changes.outputs.api == 'true'
        run: black --check ./hux/api/huxunify
      - if: always() && steps.changes.outputs.docs == 'true'
        run: black --check ./docs/source/conf.py
      - if: always() && steps.changes.outputs.dblib == 'true'
        run: black --check ./lib/huxunifylib-database/huxunifylib
      - if: always() && steps.changes.outputs.scripts == 'true'
        run: black --check ./scripts/database
      - if: always() && steps.changes.outputs.api_int_tests == 'true'
        run: black --check ./hux/integration_tests/api/test
