name: Mypy Checks
on: [pull_request]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install Pipenv
        run: pip install pipenv
      - name: Install Mypy
        run: pipenv install mypy
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            api:
              - 'hux/api/huxunify/**'
            dblib:
              - 'lib/huxunifylib-database/huxunifylib/**'
            scripts:
              - 'scripts/database/**'
#      Uncomment when mypy issues are resolved
#      - if: steps.changes.outputs.api == 'true'
#        working-directory: hux/api
#        env:
#          ARTIFACTORY_PYTHON_READ: ${{secrets.ARTIFACTORY_PYTHON_READ}}
#        run: |
#           pipenv install setuptools==56.1.0
#           pipenv install --ignore-pipfile --dev
#           pipenv run mypy --config-file=../../mypy.ini ./ --show-error-code
      - if: steps.changes.outputs.dblib == 'true'
        working-directory: lib/huxunifylib-database
        run: |
          pipenv install setuptools==56.1.0
          pipenv install --ignore-pipfile --dev
          pipenv run mypy --config-file=../../mypy.ini ./huxunifylib
#      Uncomment when mypy issues are resolved
#      - if: steps.changes.outputs.scripts == 'true'
#        working-directory: scripts
#        run: |
#          pipenv install setuptools==56.1.0
#          pipenv install --ignore-pipfile --dev
#          pipenv run mypy --config-file=../../mypy.ini ./
