name: Safety Checks
on: [pull_request]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install Safety
        run: pip install safety
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            api:
              - 'hux/api/huxunify/**'
            dblib:
              - 'lib/huxunifylib-database/huxunifylib/**'
            scripts:
              - 'scripts/database/**'
            api_intg_tests:
              - 'hux/integration_tests/api/**'
      - if: steps.changes.outputs.api == 'true'
        working-directory: hux/api
        run: safety check
      - if: always() && steps.changes.outputs.dblib == 'true'
        working-directory: lib/huxunifylib-database
        run: safety check
      - if: always() && steps.changes.outputs.scripts == 'true'
        working-directory: scripts
        run: safety check
      - if: always() && steps.changes.outputs.api_intg_tests == 'true'
        working-directory: hux/integration_tests/api
        run: safety check
